#!/usr/bin/env bash
echo "compiling library..."
make lib
echo "copying shared library..."
sudo cp lib/libspng.so /usr/lib
echo "copying header..."
sudo cp src/spng.h /usr/include
echo "cleaning..."
make clean
echo "done"
