#!/usr/bin/env bash
echo "compiling library..."
make lib
echo "copying shared library to /usr/local/lib..."
sudo cp lib/libspng.so /usr/local/lib
echo "copying header to /usr/local/include..."
sudo cp src/spng.h /usr/local/include
echo "cleaning..."
make clean
echo "done"
