pngz: pngz.c File Reference
pngz.c File Reference
#include <pthread.h>
#include <stdlib.h>
#include <stdio.h>
#include <errno.h>
#include "pngz.h"
Functions
pixel ** pngz_alloc_pixels (unsigned rows, unsigned cols)
allocate a pixel buffer.
unsigned char ** pngz_alloc_bytes (unsigned rows, unsigned cols)
allocate raw pixel byte buffer.
int pngz_free_pixels (pixel **pixels, unsigned rows)
safely free pixel buffer.
int pngz_free_bytes (unsigned char **bytes, unsigned rows)
safely free pixel buffer.
int pngz_free (pngz *z)
free a pngz structs pixels.
int pngz_pack_pixels (unsigned char **bytes_src, pixel **pixels_dest, unsigned rows, unsigned cols)
pack bytes into pixels.
int pngz_unpack_pixels (pixel **pixels_src, unsigned char **bytes_dest, unsigned rows, unsigned cols)
unpack pixels into raw byte ptrs.
int pngz_load_from (pngz *z, char *path)
load a pngz from a path directly passed into the call, just a wrapper for standard pngz_load()
int pngz_load (pngz *z)
load a pngz object into memory
int pngz_save (pngz z)
write a png back out to file, wrapper for pngz_save_as()
int pngz_save_as (pngz z, char *path)
write a png back out to file with a new name
void pngz_print (pngz z)
print a pngz ztruct contents.
void pngz_print_pixel (pixel p)
print out a single pixels rgba values in hex.
void print_indent (int indent)
void pngz_print_indent (pngz z, int indent)
print a pngz ztruct contents.
void pngz_print_pixel_indent (pixel p, int indent)
print out a single pixels rgba values.
Function Documentation
pngz_alloc_bytes()
unsigned char ** pngz_alloc_bytes (unsigned rows, unsigned cols)
allocate raw pixel byte buffer.
Parameters
rows number of rows to allocate
cols number bytes per row to allocate
Returns
a ptr to buffer, returns null and sets errno on failure
Definition at line 67 of file pngz.c.
pngz_alloc_pixels()
pixel ** pngz_alloc_pixels (unsigned rows, unsigned cols)
allocate a pixel buffer.
every pixel will be represented as a struct
Parameters
rows number of rows to allocate
cols number pixels per col to allocate
Returns
exit code, setting errno on failure
Definition at line 37 of file pngz.c.
pngz_free()
int pngz_free (pngz * z)
free a pngz structs pixels.
Parameters
z pngz* with pixels loaded into memory
Returns
exit code, error if you try to free a NULL ptr
Definition at line 164 of file pngz.c.
References pngz::height, pngz::pixels, and pngz_free_pixels().
pngz_free_bytes()
int pngz_free_bytes (unsigned char ** bytes, unsigned rows)
safely free pixel buffer.
Parameters
bytes 2D pixel bytes of size [rows][cols * 4]
rows number of rows to free
Returns
exit code
Definition at line 131 of file pngz.c.
pngz_free_pixels()
int pngz_free_pixels (pixel ** pixels, unsigned rows)
safely free pixel buffer.
Parameters
pixels 2D pixel ptr of size [rows][cols]
rows number of rows to free
Returns
exit code
Definition at line 97 of file pngz.c.
pngz_load()
int pngz_load (pngz * z)
load a pngz object into memory
Parameters
z pngz* easy png ptr to load into
Returns
exit code
Definition at line 240 of file pngz.c.
References pngz::height, pngz::path, pngz::pixels, pngz_alloc_bytes(), pngz_alloc_pixels(), pngz_free_bytes(), pngz_pack_pixels(), and pngz::width.
pngz_load_from()
int pngz_load_from (pngz * z, char * path)
load a pngz from a path directly passed into the call, just a wrapper for standard pngz_load()
Parameters
z pngz* easy png ptr to load into
path char* path to read from
Returns
exit code
Definition at line 229 of file pngz.c.
References pngz::path, and pngz_load().
pngz_pack_pixels()
int pngz_pack_pixels (unsigned char ** bytes_src, pixel ** pixels_dest, unsigned rows, unsigned cols)
pack bytes into pixels.
Parameters
bytes_src unpacked pixel byte source
pixels_dest packed pixel destination
rows rows of pixels (Y)
cols cols of pixels (X) (IN PIXELS NOT BYTES)
Returns
exit code
Definition at line 179 of file pngz.c.
References pixel::a, pixel::b, pixel::g, and pixel::r.
pngz_print()
void pngz_print (pngz z)
print a pngz ztruct contents.
Parameters
z pngz to print
Returns
void
Definition at line 401 of file pngz.c.
References pngz::height, pngz::pixels, and pngz::width.
pngz_print_indent()
void pngz_print_indent (pngz z, int indent)
print a pngz ztruct contents.
Parameters
z pngz to print
indent int for how much to indent this print
Returns
void
Definition at line 444 of file pngz.c.
References pngz::height, pngz::pixels, print_indent(), and pngz::width.
pngz_print_pixel()
void pngz_print_pixel (pixel p)
print out a single pixels rgba values in hex.
Parameters
p unsigned char* to the pixel to print
Returns
void
Definition at line 420 of file pngz.c.
References pixel::a, pixel::g, and pixel::r.
pngz_print_pixel_indent()
void pngz_print_pixel_indent (pixel p, int indent)
print out a single pixels rgba values.
Parameters
p unsigned char* to the pixel to print
indent int for how much to indent this print
Returns
void
Definition at line 468 of file pngz.c.
References pixel::a, pixel::g, print_indent(), and pixel::r.
pngz_save()
int pngz_save (pngz z)
write a png back out to file, wrapper for pngz_save_as()
Parameters
z pngz* easy png ptr to write to file
Returns
exit code
Definition at line 331 of file pngz.c.
References pngz::path, and pngz_save_as().
pngz_save_as()
int pngz_save_as (pngz z, char * path)
write a png back out to file with a new name
Parameters
path char* file path to save to
z pngz* easy png ptr to write to file
Returns
exit code
Definition at line 342 of file pngz.c.
References pngz::height, pngz::pixels, pngz_alloc_bytes(), pngz_free_bytes(), pngz_unpack_pixels(), and pngz::width.
pngz_unpack_pixels()
int pngz_unpack_pixels (pixel ** pixels_src, unsigned char ** bytes_dest, unsigned rows, unsigned cols)
unpack pixels into raw byte ptrs.
Parameters
pixels_src packed pixel source
bytes_dest unpacked byte destination
rows rows of pixels
cols cols of pixels (IN PIXELS NOT BYTES)
Returns
exit code
Definition at line 206 of file pngz.c.
References pixel::r.
print_indent()
void print_indent (int indent)
Definition at line 429 of file pngz.c.