spng: spng.h File Reference
spng.h File Reference
#include <png.h>
Classes
struct pixel
pixel in RGBA8 format.
struct spng
simplified png structure.
Typedefs
typedef struct pixel pixel
pixel in RGBA8 format.
typedef struct spng spng
simplified png structure.
Functions
pixel ** spng_alloc_pixels (unsigned rows, unsigned cols)
allocate a pixel buffer.
unsigned char ** spng_alloc_bytes (unsigned rows, unsigned cols)
allocate raw pixel byte buffer.
int spng_free_pixels (pixel **pixels, unsigned rows)
safely free pixel buffer.
int spng_free_bytes (unsigned char **bytes, unsigned rows)
safely free pixel buffer.
int spng_free (spng *p)
free a spng structs pixels.
int spng_pack_pixels (unsigned char **bytes_src, pixel **pixels_dest, unsigned rows, unsigned cols)
pack pixels with bytes.
int spng_unpack_pixels (pixel **pixels_src, unsigned char **bytes_dest, unsigned rows, unsigned cols)
unpack pixels into raw byte ptrs.
int spng_load (spng *p, char *path)
load a png image as a spng struct as RGBA8.
int spng_save (spng p, char *path)
write a png back out to file
int spng_filter (spng *p, void(*filter)(pixel *))
simple png filter.
void spng_print (spng p)
print a spng struct contents.
void spng_print_pixel (pixel p)
print out a single pixels rgba values in hex.
void spng_print_indent (spng p, int indent)
print a spng struct contents.
void spng_print_pixel_indent (pixel p, int indent)
print out a single pixels rgba values.
Typedef Documentation
pixel
typedef struct pixel pixel
pixel in RGBA8 format.
spng
typedef struct spng spng
simplified png structure.
always contains RGBA8 color. width and height are in pixels. pixel buffer is [height][width] ([row][col])
Function Documentation
spng_alloc_bytes()
unsigned char** spng_alloc_bytes (unsigned rows, unsigned cols)
allocate raw pixel byte buffer.
Parameters
rows number of rows to allocate
cols number bytes per row to allocate
Returns
a ptr to buffer, returns null and sets errno on failure
Definition at line 65 of file spng.c.
spng_alloc_pixels()
pixel** spng_alloc_pixels (unsigned rows, unsigned cols)
allocate a pixel buffer.
every pixel will be represented as a struct
Parameters
rows number of rows to allocate
cols number pixels per col to allocate
Returns
exit code, setting errno on failure
Definition at line 35 of file spng.c.
spng_filter()
int spng_filter (spng * s, void(*)(pixel *) filter)
simple png filter.
maps a function onto every pixel.
Parameters
p spng* simple png to filter
filter void(*)(unsigned char*), a filter function that take pixel ptr
Returns
exit code
Definition at line 386 of file spng.c.
References spng::height, spng::pixels, and spng::width.
spng_free()
int spng_free (spng * s)
free a spng structs pixels.
Parameters
img png* loaded into memory
Returns
exit code, error if you try to free a NULL ptr
Definition at line 159 of file spng.c.
References spng::height, spng::pixels, and spng_free_pixels().
spng_free_bytes()
int spng_free_bytes (unsigned char ** bytes, unsigned rows)
safely free pixel buffer.
Parameters
bytes 2D pixel bytes of size [rows][cols * 4]
rows number of rows to free
Returns
exit code
Definition at line 127 of file spng.c.
spng_free_pixels()
int spng_free_pixels (pixel ** pixels, unsigned rows)
safely free pixel buffer.
Parameters
pixels 2D pixel ptr of size [rows][cols]
rows number of rows to free
Returns
exit code
Definition at line 94 of file spng.c.
spng_load()
int spng_load (spng * s, char * path)
load a png image as a spng struct as RGBA8.
Parameters
path char* file path to load
p spng* simple png ptr to load into
Returns
exit code
Definition at line 225 of file spng.c.
References spng::height, spng::pixels, spng_alloc_bytes(), spng_alloc_pixels(), spng_free_bytes(), spng_pack_pixels(), and spng::width.
spng_pack_pixels()
int spng_pack_pixels (unsigned char ** bytes_src, pixel ** pixels_dest, unsigned rows, unsigned cols)
pack pixels with bytes.
Parameters
bytes_src unpacked pixel byte source
pixels_dest packed pixel destination
rows rows of pixels
cols cols of pixels (IN PIXELS NOT BYTES)
Returns
exit code
Definition at line 174 of file spng.c.
References pixel::r.
spng_print()
void spng_print (spng s)
print a spng struct contents.
Parameters
p spng to print
Returns
void
Definition at line 402 of file spng.c.
References spng::height, spng::pixels, and spng::width.
spng_print_indent()
void spng_print_indent (spng s, int indent)
print a spng struct contents.
Parameters
p spng to print
Returns
void
Definition at line 444 of file spng.c.
References spng::height, spng::pixels, print_indent(), and spng::width.
spng_print_pixel()
void spng_print_pixel (pixel p)
print out a single pixels rgba values in hex.
Parameters
p unsigned char* to the pixel to print
Returns
void
Definition at line 421 of file spng.c.
References pixel::a, pixel::g, and pixel::r.
spng_print_pixel_indent()
void spng_print_pixel_indent (pixel p, int indent)
print out a single pixels rgba values.
Parameters
p unsigned char* to the pixel to print
Returns
void
Definition at line 467 of file spng.c.
References pixel::a, pixel::g, print_indent(), and pixel::r.
spng_save()
int spng_save (spng s, char * path)
write a png back out to file
Parameters
path char* file path to save to
p spng* simple png ptr to write to file
Returns
exit code
Definition at line 321 of file spng.c.
References spng::height, spng::pixels, spng_alloc_bytes(), spng_free_bytes(), spng_unpack_pixels(), and spng::width.
spng_unpack_pixels()
int spng_unpack_pixels (pixel ** pixels_src, unsigned char ** bytes_dest, unsigned rows, unsigned cols)
unpack pixels into raw byte ptrs.
Parameters
bytes_src unpacked pixel byte source
pixels_dest packed pixel destination
rows rows of pixels
cols cols of pixels (IN PIXELS NOT BYTES)
Returns
exit code
Definition at line 202 of file spng.c.
References pixel::r.